name: Daily Market Update

on:
  schedule:
    # Schedule to run at 16:02 EST (21:02 UTC during standard time)
    - cron: "2 21 * * *"
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FINNHUB_API_KEY: ${{ secrets.FINNHUB_API_KEY }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run script
        run: |
          python main.py
